name: Build and Deploy React app

on:
  push:
    branches: [ main ]  # Körs varje gång du pushar till main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Klona koden
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Installera nyaste Node LTS (v22) + cachea dependencies från client/
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      # 3️⃣ Installera dependencies och bygg React-projektet
      - name: Build project
        working-directory: ./client
        run: |
          npm ci
          npm run build

      # 4️⃣ Ladda upp build-mappen (så att nästa jobb kan deploya den)
      - name: Upload build output
        uses: actions/upload-pages-artifact@v3
        with:
          path: client/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # 5️⃣ Deploya till GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
